name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  generate_diagram:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "vendor,.github"
